services:
  ContainerA:
    build:
      context: "."
      dockerfile: "Dockerfile"
    image: "containera"
    working_dir: "/app"
    command: ["python", "runtime_runner.py", "--config", "/app/config.json", "--container", "ContainerA"]
    cpus: 0.5
    environment:
      PYTHONUNBUFFERED: "1"
      PYTHONPATH: "/app"
    volumes:
      - "./:/app"
    ports:
      - "50591:50591"
    networks:
      - "simulation"
    restart: "unless-stopped"
  ContainerB:
    build:
      context: "."
      dockerfile: "Dockerfile"
    image: "containerb"
    working_dir: "/app"
    command: ["python", "runtime_runner.py", "--config", "/app/config.json", "--container", "ContainerB"]
    cpus: 0.5
    environment:
      PYTHONUNBUFFERED: "1"
      PYTHONPATH: "/app"
    volumes:
      - "./:/app"
    ports:
      - "50592:50592"
      - "50593:50593"
      - "50594:50594"
    networks:
      - "simulation"
    restart: "unless-stopped"
  ContainerC:
    build:
      context: "."
      dockerfile: "Dockerfile"
    image: "containerc"
    working_dir: "/app"
    command: ["python", "runtime_runner.py", "--config", "/app/config.json", "--container", "ContainerC"]
    cpus: 0.5
    environment:
      PYTHONUNBUFFERED: "1"
      PYTHONPATH: "/app"
    volumes:
      - "./:/app"
    ports:
      - "50595:50595"
      - "50596:50596"
      - "50597:50597"
      - "50598:50598"
    networks:
      - "simulation"
    restart: "unless-stopped"
  ContainerD:
    build:
      context: "."
      dockerfile: "Dockerfile"
    image: "containerd"
    working_dir: "/app"
    command: ["python", "runtime_runner.py", "--config", "/app/config.json", "--container", "ContainerD"]
    cpus: 0.5
    environment:
      PYTHONUNBUFFERED: "1"
      PYTHONPATH: "/app"
    volumes:
      - "./:/app"
    ports:
      - "50599:50599"
      - "50600:50600"
      - "50601:50601"
      - "50602:50602"
    networks:
      - "simulation"
    restart: "unless-stopped"
networks:
  simulation:
    driver: bridge
