services:
  ContainerA:
    build:
      context: "."
      dockerfile: "Dockerfile"
    image: "containera"
    working_dir: "/app"
    command: ["python", "runtime_runner.py", "--config", "/app/config.json", "--container", "ContainerA"]
    cpus: 0.5
    environment:
      PYTHONUNBUFFERED: "1"
      PYTHONPATH: "/app"
    volumes:
      - "./:/app"
    ports:
      - "60312:60312"
    networks:
      - "simulation"
    restart: "unless-stopped"
  ContainerB:
    build:
      context: "."
      dockerfile: "Dockerfile"
    image: "containerb"
    working_dir: "/app"
    command: ["python", "runtime_runner.py", "--config", "/app/config.json", "--container", "ContainerB"]
    cpus: 0.5
    environment:
      PYTHONUNBUFFERED: "1"
      PYTHONPATH: "/app"
    volumes:
      - "./:/app"
    ports:
      - "60313:60313"
      - "60314:60314"
      - "60315:60315"
    networks:
      - "simulation"
    restart: "unless-stopped"
  ContainerC:
    build:
      context: "."
      dockerfile: "Dockerfile"
    image: "containerc"
    working_dir: "/app"
    command: ["python", "runtime_runner.py", "--config", "/app/config.json", "--container", "ContainerC"]
    cpus: 0.5
    environment:
      PYTHONUNBUFFERED: "1"
      PYTHONPATH: "/app"
    volumes:
      - "./:/app"
    ports:
      - "60316:60316"
      - "60317:60317"
      - "60318:60318"
      - "60319:60319"
    networks:
      - "simulation"
    restart: "unless-stopped"
  ContainerD:
    build:
      context: "."
      dockerfile: "Dockerfile"
    image: "containerd"
    working_dir: "/app"
    command: ["python", "runtime_runner.py", "--config", "/app/config.json", "--container", "ContainerD"]
    cpus: 0.5
    environment:
      PYTHONUNBUFFERED: "1"
      PYTHONPATH: "/app"
    volumes:
      - "./:/app"
    ports:
      - "60320:60320"
      - "60321:60321"
      - "60322:60322"
      - "60323:60323"
    networks:
      - "simulation"
    restart: "unless-stopped"
networks:
  simulation:
    driver: bridge
